//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAI.NewJoineeTracker.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewJoineeInfo
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Project { get; set; }
        public string Location { get; set; }
        public string BusinessUnit { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public bool IsActive { get; set; }
    }
}
